### ISSUE TITLE
Update Questions for new Bundesnetzagentur Fragenkatalog

### ISSUE THREAD

**Issue by meyerd** [meyerd/funktrainer#9]
Up to now only the old questions are in the App.
To stay useful, the questions database should be updated.
Maybe with an option to switch between the old and the new catalogue (unclear how useful that is).

**Comment by meyerd** [comment]
Also a new class "N" was added, which would require a new section for questions.

**Comment by m-g-r** [comment]
Hi Dominik, this issue confused me a lot a month ago as I thought the funktrainer was outdated already.

I just want to add for other potential users that **as of now, Februar 23rd, 2023 the questions are still up to date** if you want to take an exam in the near future! At least in my exam this Monday these "old" questions were used. And funktrainer was a really nice program help preparing for it! :-)

Also on the webpage of the BNetzA on Amateurfunk at https://www.bundesnetzagentur.de/DE/Fachthemen/Telekommunikation/Frequenzen/SpezielleAnwendungen/Amateurfunk/start.html there is a statement at the very top with the title "Hinweis zur zweiten Verordnung zur Änderung der Amateurfunkverordnung". It states among other things that the current questionnaires remain valid for the time being ("Die bestehenden Fragenkataloge [...] behalten vorerst weiter ihre Gültigkeit.").

Look on that page for up to date information.

Cheers, Max

**Comment by meyerd** [comment]
Cheers, just out of interest checked the page again. As of August 11th, 2023, the current question set implemented in Funktrainer is till valid.

**Comment by meyerd** [comment]
Update on the topic of questions. The new questions have be published and are downloadable at 
[<https://www.bundesnetzagentur.de/DE/Fachthemen/Telekommunikation/Frequenzen/SpezielleAnwendungen/Amateurfunk/start.html]. Work to integrate those will commence ...
